name: Ejercicio1 workflow

on: push

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v5
  
      - name: Instalar pytest
        run: pip install pytest
  
      - name: Ejecutar los tests
        run: pytest test.py
